# Generated by Django 5.1.4 on 2025-01-21 12:38

import django.db.models.deletion
import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.CharField(max_length=50, verbose_name='Описание')),
                ('fullDescription', models.TextField(max_length=1000, verbose_name='Полное описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('freeDelivery', models.BooleanField(default=False, verbose_name='Бесплатная доставка')),
                ('available', models.BooleanField(default=True, verbose_name='Доступность')),
                ('index', models.IntegerField(default=1, verbose_name='Индекс сортировки')),
                ('count', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('rating', models.IntegerField(default=0, verbose_name='Рейтинг')),
                ('limited', models.BooleanField(default=False, verbose_name='Лимитированный')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=products.models.product_images_dir_path, verbose_name='Картинка')),
                ('content', models.CharField(max_length=50, verbose_name='Альтернативная надпись')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product', verbose_name='Товар')),
            ],
        ),
    ]
