# Generated by Django 5.1.4 on 2025-01-21 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salePrice', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена по скидке')),
                ('dateFrom', models.CharField(max_length=50, verbose_name='Начало распродажи')),
                ('dateTo', models.CharField(max_length=50, verbose_name='Конец распродажи')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='products.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Распродажа',
                'verbose_name_plural': 'Распродажи',
            },
        ),
    ]
