# Generated by Django 5.1.4 on 2025-01-21 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0006_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('fullName', models.CharField(max_length=100, null=True, verbose_name='Полное имя')),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone', models.CharField(max_length=20, null=True, verbose_name='Номер телефона')),
                ('city', models.CharField(max_length=15, null=True, verbose_name='Город')),
                ('address', models.CharField(max_length=40, null=True, verbose_name='Адрес')),
                ('deliveryType', models.IntegerField(default=0, null=True, verbose_name='Тип доставки')),
                ('paymentType', models.IntegerField(default=0, null=True, verbose_name='Тип платежа')),
                ('status', models.IntegerField(default=0, null=True, verbose_name='Статус')),
                ('products', models.ManyToManyField(related_name='orders', to='products.product', verbose_name='Товары')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
