# Generated by Django 5.1.4 on 2025-01-21 12:55

import django.db.models.deletion
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_sale'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=users.models.images_dir_path)),
                ('content', models.CharField(max_length=50)),
                ('category', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image', to='products.category')),
                ('profile', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avatar', to='users.profile')),
                ('subcategory', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image', to='products.subcategory')),
            ],
        ),
    ]
