# Generated by Django 5.1.4 on 2025-01-21 12:55

import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(validators=[users.validators.validate_even, users.validators.validate_length], verbose_name='Номер карты')),
                ('name', models.CharField(max_length=120, verbose_name='Имя на карте')),
                ('month', models.CharField(max_length=2, verbose_name='Месяц')),
                ('year', models.CharField(max_length=4, verbose_name='Год')),
                ('code', models.CharField(max_length=3, verbose_name='CVV/CVC код')),
            ],
            options={
                'verbose_name': 'Платежная система',
                'verbose_name_plural': 'Платежные системы',
            },
        ),
    ]
